# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
SetSeed_cpp <- function(seed, stream = 0L) {
    invisible(.Call('_rwmcouplings_SetSeed_cpp', PACKAGE = 'rwmcouplings', seed, stream))
}

#' @export
rwm_cpp <- function(target_params, sampler_params, theta0, iter, thin) {
    .Call('_rwmcouplings_rwm_cpp', PACKAGE = 'rwmcouplings', target_params, sampler_params, theta0, iter, thin)
}

#' @export
mala_cpp <- function(target_params, sampler_params, theta0, iter, thin) {
    .Call('_rwmcouplings_mala_cpp', PACKAGE = 'rwmcouplings', target_params, sampler_params, theta0, iter, thin)
}

#' @export
rwm_twoscalegcrn_cpp <- function(target_params, sampler_params, x0, y0, iter) {
    .Call('_rwmcouplings_rwm_twoscalegcrn_cpp', PACKAGE = 'rwmcouplings', target_params, sampler_params, x0, y0, iter)
}

#' @export
rwm_twoscalegcrefl_cpp <- function(target_params, sampler_params, x0, y0, iter) {
    .Call('_rwmcouplings_rwm_twoscalegcrefl_cpp', PACKAGE = 'rwmcouplings', target_params, sampler_params, x0, y0, iter)
}

#' @export
mala_twoscalecrn_cpp <- function(target_params, sampler_params, x0, y0, iter) {
    .Call('_rwmcouplings_mala_twoscalecrn_cpp', PACKAGE = 'rwmcouplings', target_params, sampler_params, x0, y0, iter)
}

#' Sample the latent variables from the model
#'
#' @export
SampleLatentVariables <- function(T, sig, phi) {
    .Call('_rwmcouplings_SampleLatentVariables', PACKAGE = 'rwmcouplings', T, sig, phi)
}

#' RWM algorithm
#'
#' @export
svmRWM <- function(x0, y, beta, sigma, phi, h, iter) {
    .Call('_rwmcouplings_svmRWM', PACKAGE = 'rwmcouplings', x0, y, beta, sigma, phi, h, iter)
}

#' RWM algorithms, with CRN coupling
#'
#' @export
svmCRNRWM <- function(x0, y0, y_data, beta, sigma, phi, h, iter, thin) {
    .Call('_rwmcouplings_svmCRNRWM', PACKAGE = 'rwmcouplings', x0, y0, y_data, beta, sigma, phi, h, iter, thin)
}

#' RWM algorithms, with reflection-maximal coupling
#'
#' @export
svmReflMaxRWM <- function(x0, y0, y_data, beta, sigma, phi, h, iter, thin) {
    .Call('_rwmcouplings_svmReflMaxRWM', PACKAGE = 'rwmcouplings', x0, y0, y_data, beta, sigma, phi, h, iter, thin)
}

#' RWM algorithms, with two-scale coupling using GCRN when (|x-y|^2 >= thresh) and using reflection-maximal coupling when (|x-y|^2 < thresh)
#'
#' @export
svmTwoScaleGCRNRWM <- function(x0, y0, y_data, beta, sigma, phi, h, iter, thin, thresh) {
    .Call('_rwmcouplings_svmTwoScaleGCRNRWM', PACKAGE = 'rwmcouplings', x0, y0, y_data, beta, sigma, phi, h, iter, thin, thresh)
}

#' Two-scale coupling, with corrected reflection and reflection.
#' @export
svmTwoScaleGCReflRWM <- function(x0, y0, y_data, beta, sigma, phi, h, iter, thin, thresh) {
    .Call('_rwmcouplings_svmTwoScaleGCReflRWM', PACKAGE = 'rwmcouplings', x0, y0, y_data, beta, sigma, phi, h, iter, thin, thresh)
}

#' GCRN-coupled RWM algorithms targeting SVM and a Laplace approximation
#'
#' @export
svmLaplaceGCRNRWM <- function(x0, y0, y_data, beta, sigma, phi, mu, Omega, Omega_chol, h, iter, thin) {
    .Call('_rwmcouplings_svmLaplaceGCRNRWM', PACKAGE = 'rwmcouplings', x0, y0, y_data, beta, sigma, phi, mu, Omega, Omega_chol, h, iter, thin)
}

#' CRN-coupled RWM algorithms targeting SVM and a Laplace approximation
#'
#' @export
svmLaplaceCRNRWM <- function(x0, y0, y_data, beta, sigma, phi, mu, Omega, Omega_chol, h, iter, thin) {
    .Call('_rwmcouplings_svmLaplaceCRNRWM', PACKAGE = 'rwmcouplings', x0, y0, y_data, beta, sigma, phi, mu, Omega, Omega_chol, h, iter, thin)
}

#' Reflection-coupled RWM algorithms targeting SVM and a Laplace approximation
#'
#' @export
svmLaplaceReflRWM <- function(x0, y0, y_data, beta, sigma, phi, mu, Omega, Omega_chol, h, iter, thin) {
    .Call('_rwmcouplings_svmLaplaceReflRWM', PACKAGE = 'rwmcouplings', x0, y0, y_data, beta, sigma, phi, mu, Omega, Omega_chol, h, iter, thin)
}

#' Corrected reflection
#'
#' @export
svmLaplaceGCReflRWM <- function(x0, y0, y_data, beta, sigma, phi, mu, Omega, Omega_chol, h, iter, thin) {
    .Call('_rwmcouplings_svmLaplaceGCReflRWM', PACKAGE = 'rwmcouplings', x0, y0, y_data, beta, sigma, phi, mu, Omega, Omega_chol, h, iter, thin)
}

#' Two-scale corrected reflection
#'
#' @export
svmLaplacetwoscaleGCReflRWM <- function(x0, y0, y_data, beta, sigma, phi, mu, Omega, Omega_chol, h, iter, thin, thresh) {
    .Call('_rwmcouplings_svmLaplacetwoscaleGCReflRWM', PACKAGE = 'rwmcouplings', x0, y0, y_data, beta, sigma, phi, mu, Omega, Omega_chol, h, iter, thin, thresh)
}

#' @export
logpi_cpp <- function(target_params, theta) {
    .Call('_rwmcouplings_logpi_cpp', PACKAGE = 'rwmcouplings', target_params, theta)
}

#' @export
gradlogpi_cpp <- function(target_params, theta) {
    .Call('_rwmcouplings_gradlogpi_cpp', PACKAGE = 'rwmcouplings', target_params, theta)
}

#' @export
hesslogpi_cpp <- function(target_params, theta) {
    .Call('_rwmcouplings_hesslogpi_cpp', PACKAGE = 'rwmcouplings', target_params, theta)
}

